drop table if exists dish cascade;
drop table if exists restaurant cascade;
drop table if exists menu cascade;
drop table if exists user_role cascade;
drop table if exists users cascade;

create table users
(
    id         int generated by default as identity,
    name       varchar(128)            not null,
    email      varchar(255)            not null,
    password   varchar(255)            not null,
    surname    varchar(255)            not null,
    registered timestamp default now() not null,
    primary key (id)
);

create unique index users_unique_email_idx on users (email);

create table user_role
(
    user_id int not null,
    role    varchar(255),
    constraint user_roles_idx unique (user_id, role),
    foreign key (user_id) references users (id)
);

create table menu
(
    id   int generated by default as identity,
    name varchar(128) not null,
    primary key (id)
);

create table restaurant
(
    id          int generated by default as identity,
    name        varchar(128) not null,
    description varchar(255) not null,
    menu_id     int          not null,
    primary key (id),
    foreign key (menu_id) references menu (id),
    constraint menu_restaurant_idx unique (menu_id, name)
);
create unique index restaurant_unique_menu_id_idx on restaurant (menu_id);

create table dish
(
    id      int generated by default as identity,
    name    varchar(128) not null,
    price   float(53)    not null,
    menu_id int          not null,
    constraint menu_dish_idx unique (menu_id, name),
    primary key (id),
    foreign key (menu_id) references menu (id)
);
create unique index dish_unique_menu_id_idx on dish (menu_id);